#!/bin/bash
#Instagram Downloader with no option! :D It can download both pictures and videos, just give it the share url!
#There is no license
#Contact: hamedsepehry[at]yahoo[dot]com

version="0.1.1"
network_timeout=15
instalink=$1
instapattern="https?://(www\.)?instagram\.com/.*"

function show_help {
    echo "Instagram Downloader $version, instagram share url downloader."
}

function show_error {
    echo "instadl: $1" >&2
}

function show_usage {
    echo "Usage: instadl [-h] [Instagram Share URL]"
    echo "Example: instadl https://instagram.com/p/9aagaUKT7-/"
    echo ""
    echo "Try ‘instadl -h’ for help."
}

if [ "$instalink" == "" ] | [ "$instalink" == "-h" ] #if there was no link
then
    show_help
    show_usage
	exit 1
elif [[ ! $instalink =~ $instapattern ]] #if the link was wrong
then
    show_error "invalid instagram share url."
    show_usage >&2
	exit 2
else
	IFS=''
    pagesource=$(wget -T $network_timeout -qO - $instalink) #get source of the page
    if [ "$?" != "0" ]
    then
        show_error "failed to fetch ‘$instalink’"
        exit 3
    fi
	if [ "$(echo $pagesource | egrep mp4)" = "" ] #check if there is a pic or vid to download
	then #get img download link
		dllink="$(echo $pagesource | egrep jpg | head -1 | egrep -o "http.+jpg")"
	else #get vid download link
		dllink="$(echo $pagesource | egrep mp4 | head -1 | egrep -o "http.+mp4")"
	fi
	wget -T $network_timeout -qc "$dllink" #download file via wget, u can change it if u want and replace with other download apps like axel or aria2c
    if [ "$?" != "0" ]
    then
        show_error "failed to download ‘$dllink’"
        exit 4
    fi
fi
